#!/bin/sh
if [ -z "${IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/40_luci-frpc ) && rm -f /etc/uci-defaults/40_luci-frpc
fi

chmod 755 "${IPKG_INSTROOT}/etc/init.d/frpc" >/dev/null 2>&1
ln -sf "../init.d/frpc" "${IPKG_INSTROOT}/etc/rc.d/S99frpc" >/dev/null 2>&1
exit 0
